<?php
// $Id:
/**
 * @file
 */

/**
 * Implementation of hook_views_api().
 */
function views_infinite_scroll_views_api() {
  return array('api' => '3.0-alpha1');
}

/**
 * Implementation of hook_theme().
 */
function views_infinite_scroll_theme() {
  $path = drupal_get_path('module', 'views_infinite_scroll');

  // Some quasi clever array merging here.
  $base = array(
    'file' => 'views_infinite_scroll_theme.inc',
    'path' => "$path/theme",
  );

  // Our extra version of pager from pager.inc
  $hooks['views_infinite_scroll_pager'] = $base + array(
    'arguments' => array('tags' => array(), 'limit' => 10, 'element' => 0, 'parameters' => array()),
    'pattern' => 'views_infinite_scroll_pager__',
  );
  return $hooks;
}
